In [2]:
from google.colab import files

In [4]:
uploaded = files.upload() # fazendo o upload do conjunto de dados

Saving p33.xlsx to p33.xlsx

In [3]:
import pandas as pd #importando a biblioteca

In [12]:
tecal = pd.read_excel('p33.xlsx') #lendo o conjunto de dados

In [14]:
tecal.head() # mostrando as 5 primeiras linhas

,id,idade,linhas,temp_cli,renda,fatura,temp_rsd,local,tvcabo,debaut,cancel
0,TC-0001,51,3,26,5320,543,7.3,A,sim,nao,nao
1,TC-0002,36,2,16,5620,482,4.5,A,sim,nao,nao
2,TC-0003,35,1,15,4860,593,4.8,A,nao,nao,nao
3,TC-0004,44,1,16,5400,646,6.3,C,sim,sim,sim
4,TC-0005,40,1,22,6590,1184,6.2,C,sim,nao,nao

In [16]:
tabela_frequencia_tecal = pd.DataFrame({
    'Frequência Absoluta': tecal['cancel'].value_counts(),
    'Frequência Relativa (%)': tecal['cancel'].value_counts(normalize=True) * 100
    })
# criando uma tabela de frequência da variável "cancel"

In [17]:
print(tabela_frequencia_tecal) # mostrando a tabela de frequência

        Frequência Absoluta  Frequência Relativa (%)
cancel
nao                    1523                    76.15
sim                     477                    23.85

In [ ]:
!pip install imbalanced-learn # instalando o pacote imbalanced-learn para aplicar o balanceamento

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.0)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.2)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [35]:
from imblearn.over_sampling import RandomOverSampler

In [36]:
X = tecal.drop('cancel', axis=1)  # todas as variáveis explicativas
y = tecal['cancel']               # variável resposta

In [37]:
tecal_balanceamento = RandomOverSampler(sampling_strategy='auto', random_state=42)
X_resampled, y_resampled = tecal_balanceamento.fit_resample(X, y) # aplicando o balanceamento

In [38]:
tecal_balanceado = pd.concat([pd.DataFrame(X_resampled), pd.DataFrame(y_resampled, columns=['cancel'])], axis=1) # juntar novamente em um dataframe balanceado

In [39]:
print(tecal_balanceado['cancel'].value_counts())
print(len(tecal_balanceado)) # verificando o novo balanceamento

cancel
nao    1523
sim    1523
Name: count, dtype: int64
3046

In [40]:
tecal_balanceado = tecal_balanceado.sample(n=3000, random_state=42) # ajustando para ter aproximadamente 3000 obeseravções

In [30]:
print(tecal_balanceado['cancel'].value_counts())
print(len(tecal_balanceado))

cancel
sim    1502
nao    1498
Name: count, dtype: int64
3000

In [31]:
print(tecal_balanceado)

           id  idade  linhas  temp_cli  renda  fatura  temp_rsd local tvcabo  \
1018  TC-1019     31       1        22   6030     757       5.1     B    sim
642   TC-0643     41       2        22   9320     651       5.3     C    nao
2241  TC-0930     37       2        12   5730     781       3.8     B    sim
1377  TC-1378     35       1        12   5130     144       2.6     C    nao
2221  TC-1967     31       3        15  10170     625       1.5     A    nao
...       ...    ...     ...       ...    ...     ...       ...   ...    ...
600   TC-0601     59       2        48  30000    4000       6.6     A    sim
2435  TC-0014     28       1        15   5950     617       4.2     A    sim
1297  TC-1298     28       1        19   5160    1185       3.8     D    sim
2214  TC-0202     31       2        12   5530     504       4.6     A    sim
2888  TC-0606     36       1        12   5510     613       7.9     C    nao

     debaut cancel
1018    sim    sim
642     sim    nao
2241    sim    sim
1377    nao    sim
2221    sim    sim
...     ...    ...
600     sim    sim
2435    nao    sim
1297    nao    sim
2214    sim    sim
2888    nao    sim

[3000 rows x 11 columns]

In [32]:
tecal_balanceado

,id,idade,linhas,temp_cli,renda,fatura,temp_rsd,local,tvcabo,debaut,cancel
1018,TC-1019,31,1,22,6030,757,5.1,B,sim,sim,sim
642,TC-0643,41,2,22,9320,651,5.3,C,nao,sim,nao
2241,TC-0930,37,2,12,5730,781,3.8,B,sim,sim,sim
1377,TC-1378,35,1,12,5130,144,2.6,C,nao,nao,sim
2221,TC-1967,31,3,15,10170,625,1.5,A,nao,sim,sim
...,...,...,...,...,...,...,...,...,...,...,...
600,TC-0601,59,2,48,30000,4000,6.6,A,sim,sim,sim
2435,TC-0014,28,1,15,5950,617,4.2,A,sim,nao,sim
1297,TC-1298,28,1,19,5160,1185,3.8,D,sim,nao,sim
2214,TC-0202,31,2,12,5530,504,4.6,A,sim,sim,sim
2888,TC-0606,36,1,12,5510,613,7.9,C,nao,nao,sim

In [34]:
print(tecal.describe()) # antes do balanceamento

             idade     linhas     temp_cli         renda      fatura  \
count  2000.000000  2000.0000  2000.000000   2000.000000  2000.00000
mean     38.420500     1.6465    20.613000   7645.110000   748.83200
std       8.003918     0.7790     7.166024   3795.558591   627.12678
min      23.000000     1.0000    12.000000   4210.000000     9.00000
25%      32.000000     1.0000    15.000000   5420.000000   326.75000
50%      38.000000     1.0000    19.000000   6400.000000   582.00000
75%      44.000000     2.0000    25.000000   8377.500000   972.50000
max      61.000000     3.0000    50.000000  30000.000000  4000.00000

          temp_rsd
count  2000.000000
mean      5.011500
std       2.018644
min       0.100000
25%       3.600000
50%       5.000000
75%       6.400000
max      12.900000

In [33]:
print(tecal_balanceado.describe()) #depois do balanceamento

             idade       linhas     temp_cli         renda       fatura  \
count  3000.000000  3000.000000  3000.000000   3000.000000  3000.000000
mean     37.518333     1.702000    19.449667   7432.740000   844.061000
std       8.024450     0.794611     6.878219   3700.226216   682.675744
min      23.000000     1.000000    12.000000   4210.000000     9.000000
25%      31.000000     1.000000    14.000000   5330.000000   372.000000
50%      36.000000     1.000000    18.000000   6220.000000   669.000000
75%      43.000000     2.000000    23.000000   8160.000000  1110.000000
max      61.000000     3.000000    50.000000  30000.000000  4000.000000

          temp_rsd
count  3000.000000
mean      5.038733
std       1.983412
min       0.100000
25%       3.700000
50%       5.000000
75%       6.400000
max      12.900000